<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '10',
    'typeid' => '0',
    'title' => '激发个角色日立刻关机',
    'style' => '',
    'thumb' => 'http://localhost:89/uploadfile/2016/0314/20160314021106737.jpg',
    'keywords' => '日立 角色',
    'description' => '就覅就发文件发放假哇饿就发来看我发觉啊放假额看来减肥啊减肥法啊万分饥饿啊看来我发觉',
    'posids' => '0',
    'url' => 'http://localhost:89/index.php?m=content&c=index&a=show&catid=10&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457935826',
    'updatetime' => '1458004460',
    'hitsid' => 'c-1-4',
    'views' => '2',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '10',
    'typeid' => '0',
    'title' => 'text1',
    'style' => '',
    'thumb' => 'http://localhost:89/uploadfile/2016/0314/20160314020032720.jpg',
    'keywords' => 'text1',
    'description' => 'jfaisojfaisjflw',
    'posids' => '0',
    'url' => 'http://localhost:89/index.php?m=content&c=index&a=show&catid=10&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457934560',
    'updatetime' => '1457935193',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '10',
    'typeid' => '0',
    'title' => 'test2',
    'style' => '',
    'thumb' => 'http://localhost:89/uploadfile/2016/0314/20160314020748402.jpg',
    'keywords' => 'test2',
    'description' => 'awfewaf',
    'posids' => '0',
    'url' => 'http://localhost:89/index.php?m=content&c=index&a=show&catid=10&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457935648',
    'updatetime' => '1457935926',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>