<?php
return array (
  7 => 
  array (
    'id' => '7',
    'catid' => '12',
    'typeid' => '0',
    'title' => '定制服务',
    'style' => '',
    'thumb' => 'http://tqlmm.com/uploadfile/2016/0321/20160321102711619.png',
    'keywords' => '私人定制',
    'description' => '私人定制',
    'posids' => '0',
    'url' => 'http://tqlmm.com/index.php?m=content&c=index&a=show&catid=12&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457938801',
    'updatetime' => '1458031003',
    'hitsid' => 'c-1-7',
    'views' => '7',
    'yesterdayviews' => '3',
    'dayviews' => '4',
    'weekviews' => '7',
    'monthviews' => '7',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '12',
    'typeid' => '0',
    'title' => '公关活动',
    'style' => '',
    'thumb' => 'http://tqlmm.com/uploadfile/2016/0321/20160321102953961.png',
    'keywords' => '婚庆，开业庆典，促销活动',
    'description' => '婚庆 |开业庆典 |促销活动',
    'posids' => '0',
    'url' => 'http://tqlmm.com/index.php?m=content&c=index&a=show&catid=12&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457939766',
    'updatetime' => '1458031007',
    'hitsid' => 'c-1-8',
    'views' => '3',
    'yesterdayviews' => '2',
    'dayviews' => '1',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '12',
    'typeid' => '0',
    'title' => '广告传媒',
    'style' => '',
    'thumb' => 'http://tqlmm.com/uploadfile/2016/0321/20160321103147520.png',
    'keywords' => '传媒 广告',
    'description' => '企业宣传片 |广告片 |报纸广告 |杂志广告 |户外广告',
    'posids' => '0',
    'url' => 'http://tqlmm.com/index.php?m=content&c=index&a=show&catid=12&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458030583',
    'updatetime' => '1458031820',
    'hitsid' => 'c-1-18',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '12',
    'typeid' => '0',
    'title' => '品牌设计',
    'style' => '',
    'thumb' => 'http://tqlmm.com/uploadfile/2016/0321/20160321102044563.png',
    'keywords' => '标志设计 画册 包装设计',
    'description' => '标志设计 |画册 |包装设计 |空间设计',
    'posids' => '0',
    'url' => 'http://tqlmm.com/index.php?m=content&c=index&a=show&catid=12&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458030619',
    'updatetime' => '1458030644',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '12',
    'typeid' => '0',
    'title' => '全部服务',
    'style' => '',
    'thumb' => 'http://tqlmm.com/uploadfile/2016/0321/20160321101426921.png',
    'keywords' => '全部服务',
    'description' => '所有服务',
    'posids' => '0',
    'url' => 'http://tqlmm.com/index.php?m=content&c=index&a=show&catid=12&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458032970',
    'updatetime' => '1458033019',
    'hitsid' => 'c-1-20',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '12',
    'typeid' => '0',
    'title' => '网络营销',
    'style' => '',
    'thumb' => 'http://tqlmm.com/uploadfile/2016/0321/20160321015125142.png',
    'keywords' => '网络营销',
    'description' => '整合网络资源营销',
    'posids' => '0',
    'url' => 'http://tqlmm.com/index.php?m=content&c=index&a=show&catid=12&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458539387',
    'updatetime' => '1458539488',
    'hitsid' => 'c-1-23',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>