<?php
return array (
  10 => 
  array (
    'id' => '10',
    'catid' => '14',
    'typeid' => '0',
    'title' => '小动物保护协会',
    'style' => '',
    'thumb' => 'http://localhost:89/uploadfile/2016/0314/20160314040422538.jpg',
    'keywords' => '小动 协会',
    'description' => '小动物好可怜，大家来保护他小动物好可怜，大家来保护他小动物好可怜，大家来保护他小动物好可怜，大家来保护他小动物好可怜，大家来保护他小动物好可怜，大家来保护他小动物好可怜，',
    'posids' => '0',
    'url' => 'http://localhost:89/index.php?m=content&c=index&a=show&catid=14&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457942604',
    'updatetime' => '1457944813',
    'hitsid' => 'c-1-10',
    'views' => '10',
    'yesterdayviews' => '0',
    'dayviews' => '10',
    'weekviews' => '10',
    'monthviews' => '10',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '14',
    'typeid' => '0',
    'title' => '打老虎',
    'style' => '',
    'thumb' => 'http://localhost:89/uploadfile/2016/0314/20160314043512905.jpg',
    'keywords' => '老虎',
    'description' => '发违法发违法饿啊我发俄方a  f  we  fa  w',
    'posids' => '0',
    'url' => 'http://localhost:89/index.php?m=content&c=index&a=show&catid=14&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457944485',
    'updatetime' => '1457944829',
    'hitsid' => 'c-1-11',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
);
?>